import fs from 'fs/promises';
import fse from 'fs-extra'; // For fs.outputFile
import path from 'path';
import { fileURLToPath } from 'url';
import * as cheerio from 'cheerio';
import { v4 as uuidv4 } from 'uuid';

/*
    SVG Utils for EJS Views 
    Version: 1.4.0

    Falta crear script que podria usar plugin gulp-inline-svg o similar
    y haga el “inline” de los SVGs durante el deploy (sin tocar los views manualmente).

    https://chatgpt.com/c/6835b297-d880-800b-a7cd-2a284003cd40 -Coder-
*/

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const GENERATED_SVGS_JSON = path.join(__dirname, '..', 'etc', 'autogenerated_svg.json');

export class SVGUtils {
    constructor(config = {}) {
        this.svgRegex = /<svg[\s\S]*?<\/svg>/gi;
        this.viewsDir = config.viewsDir || path.join(__dirname, '..', 'views');
        this.outputDir = config.outputDir || path.join(__dirname, '..', 'public', 'assets', 'img');
        this.testMode = config.testMode ?? true;
        this.killDuplicatedSVG = false;
        this.generatedMap = new Map(); // Map<normalizedSVG, filename>

        this.outputDir   = path.resolve(this.outputDir);
        this.projectRoot = path.resolve(this.outputDir, '..', '..', '..'); 

        console.log(`Output Img Path: ${this.outputDir}`);
        console.log(`Project Path: ${this.projectRoot}`);
    }

    config(options = {}) {
        if (options.viewsDir) {
            this.viewsDir = options.viewsDir;
        }
        if (options.outputDir) {
            this.outputDir = options.outputDir;
        }
        if (options.testMode !== undefined) {
            this.testMode = options.testMode;
        }
        if (options.killDuplicatedSVG !== undefined) {
            this.killDuplicatedSVG = options.killDuplicatedSVG;
        }

        if (this.generatedMap.size > 0) {
            this.resetGeneratedMap();
        }
    }

    setKillDuplicatedSVG(value = true) {
        this.killDuplicatedSVG = value;
    }

    setTestModeOff() {
        this.testMode = false;
    }

    async loadGeneratedSVGMap() {
        try {
            const data = await fs.readFile(GENERATED_SVGS_JSON, 'utf8');
            const parsed = JSON.parse(data);
            for (const [svg, filename] of Object.entries(parsed)) {
                this.generatedMap.set(svg, filename);
            }
        } catch {
            this.generatedMap.clear();
        }
    }

    async saveGeneratedSVGMap() {
        const obj = Object.fromEntries(this.generatedMap);
        await fse.ensureFile(GENERATED_SVGS_JSON);
        await fs.writeFile(GENERATED_SVGS_JSON, JSON.stringify(obj, null, 2), 'utf8');
    }

    normalizeSVG(svg) {
        return svg
            .replace(/\s+/g, ' ')
            .replace(/>\s+</g, '><')
            .replace(/"/g, "'")
            .trim();
    }

    async findEjsFiles(dir) {
        const entries = await fs.readdir(dir, { withFileTypes: true });
        const files = await Promise.all(entries.map(async entry => {
            const fullPath = path.join(dir, entry.name);
            if (entry.isDirectory()) {
                return this.findEjsFiles(fullPath);
            } else if (entry.isFile() && fullPath.endsWith('.ejs')) {
                return [fullPath];
            }
            return [];
        }));
        return files.flat();
    }

    async listEmbeddedSVGs() {
        const svgMap = new Map();
        const files = await this.findEjsFiles(this.viewsDir);

        for (const filePath of files) {
            const content = await fs.readFile(filePath, 'utf8');
            const matches = content.match(this.svgRegex);
            if (matches && matches.length > 0) {
                matches.forEach((match, index) => {
                    const normalized = this.normalizeSVG(match);
                    const preview = match.replace(/\s+/g, ' ').slice(0, 100);

                    const entry = {
                        file: path.relative(process.cwd(), filePath),
                        index: index + 1,
                        preview
                    };

                    if (!svgMap.has(normalized)) {
                        svgMap.set(normalized, []);
                    }
                    svgMap.get(normalized).push(entry);
                });
            }
        }

        return svgMap;
    }

    async extractAndReplaceSVGs() {
        await this.loadGeneratedSVGMap();

        const ejsFiles = await this.findEjsFiles(this.viewsDir);
        let totalExtracted = 0;

        for (const filePath of ejsFiles) {
            let content = await fs.readFile(filePath, 'utf8');
            let modified = false;

            // Encuentra todos los <svg>...</svg> en el contenido
            const matches = content.match(this.svgRegex);

            if (matches && matches.length > 0) {
            for (const match of matches) {
                const normalizedSVG = this.normalizeSVG(match);

                let filename;
                if (this.killDuplicatedSVG && this.generatedMap.has(normalizedSVG)) {
                filename = this.generatedMap.get(normalizedSVG);
                } else {
                filename = `__generated-${uuidv4()}.svg`;
                const outputPath = path.join(this.outputDir, filename);
                await fse.outputFile(outputPath, normalizedSVG);
                this.generatedMap.set(normalizedSVG, filename);
                totalExtracted++;
                }

                // Reemplaza el <svg> con un <img>
                const imgTag = `<img src="/assets/img/${filename}" alt="Embedded SVG" />`;
                content = content.replace(match, imgTag);
                modified = true;
            }
            }

            if (modified) {
            const outputFile = this.testMode
                ? path.join(path.dirname(filePath), `__${path.basename(filePath)}`)
                : filePath;

            await fs.writeFile(outputFile, content, 'utf8');
            console.log(`✅ Processed ${path.relative(process.cwd(), outputFile)}`);
            }
        }

        await this.saveGeneratedSVGMap();
        console.log(`\n🎯 Total new SVGs extracted: ${totalExtracted}`);
    }

    async deleteGeneratedSVGs(all = false) {
        await this.loadGeneratedSVGMap();

        const filesToKeep = new Set();
        if (!all) {
            for (const filename of this.generatedMap.values()) {
                filesToKeep.add(filename);
            }
        }

        const allFiles = await fs.readdir(this.outputDir);
        let deletedCount = 0;

        for (const file of allFiles) {
            if (file.startsWith('__generated-') && file.endsWith('.svg')) {
                if (all || !filesToKeep.has(file)) {
                    const fullPath = path.join(this.outputDir, file);
                    await fs.unlink(fullPath);
                    deletedCount++;
                }
            }
        }

        if (all) {
            this.generatedMap.clear();
            await fs.unlink(GENERATED_SVGS_JSON).catch(() => {});
        }

        console.log(`🗑️  Deleted ${deletedCount} autogenerated SVG(s).`);
    }


    /*
        Borra el contenido del Map en memoria, y opcionalmente también borra el contenido 
        del archivo autogenerated_svg.json (si se le pasa true como parámetro).
    */
    resetGeneratedMap(clearFile = false) {
        this.generatedMap.clear();
        if (clearFile) {
            return fs.writeFile(GENERATED_SVGS_JSON, '{}', 'utf8');
        }
    }

    // Borra todos los archivos que comienzan con "__" y terminan con ".ejs" en el directorio de vistas.
    async killUnderscoreFiles(dir = this.viewsDir) {
        const entries = await fs.readdir(dir, { withFileTypes: true });

        for (const entry of entries) {
            const fullPath = path.join(dir, entry.name);

            if (entry.isDirectory()) {
                await this.killUnderscoreFiles(fullPath);
            } else if (entry.isFile() && entry.name.startsWith('__') && entry.name.endsWith('.ejs')) {
                await fs.unlink(fullPath);
                console.log(`🗑️ Deleted: ${path.relative(process.cwd(), fullPath)}`);
            }
        }
    }

    printEmbeddedSVGs(svgMap) {
        for (const [normalized, entries] of svgMap.entries()) {
            entries.forEach(({ file, index, preview }, i) => {
                if (i === 0) {
                    console.log(`📁 ${file} — ${entries.length} SVG(s) found`);
                }
                console.log(`   └─ [${index}] ${preview}...`);
            });
            console.log('');
        }
    }

    listDuplicateSVGs(svgMap) {
        const duplicates = new Map();
        for (const [normalized, entries] of svgMap.entries()) {
            if (entries.length > 1) {
                duplicates.set(normalized, entries);
            }
        }
        return duplicates;
    }

    printDuplicateSVGs(duplicates) {
        if (duplicates.size === 0) {
            console.log('✅ No duplicated SVGs found.\n');
            return;
        }

        console.log(`🔁 Checking for duplicated SVGs...\n`);

        for (const [normalized, entries] of duplicates.entries()) {
            console.log(`⚠️  Duplicate SVG found in ${entries.length} locations:`);
            entries.forEach(({ file, index }) => {
                console.log(`   └─ ${file} [#${index}]`);
            });
            console.log('');
        }

        console.log(`⚠️  ${duplicates.size} duplicated SVG(s) found across views.\n`);
    }

    async replaceCurrentColorAttributes(svgPath, { strokeColor = null, fillColor = null } = {}) {
        console.log(`🔍 Processing SVG: ${svgPath}`);
        
        try {
            let content = await fs.readFile(svgPath, 'utf8');
            console.log(`Original content: ${content}`);
            let modified = false;

            if (strokeColor) {
                const normalizedStroke = strokeColor.startsWith('#') ? strokeColor : `#${strokeColor}`;
                // Regex más específica para evitar matches parciales
                const regex = /\bstroke\s*=\s*'currentColor'/gi;
                const newContent = content.replace(regex, `stroke='${normalizedStroke}'`);
                if (newContent !== content) {
                    content = newContent;
                    modified = true;
                    console.log(`🎨 Replaced stroke='currentColor' with stroke='${normalizedStroke}'`);
                } else {
                    console.log(`⚠️ No match for stroke='currentColor'`);
                }
            }

            if (fillColor) {
                const normalizedFill = fillColor.startsWith('#') ? fillColor : `#${fillColor}`;
                // Regex más específica para evitar matches parciales
                const regex = /\bfill\s*=\s*'currentColor'/gi;
                const newContent = content.replace(regex, `fill='${normalizedFill}'`);
                if (newContent !== content) {
                    content = newContent;
                    modified = true;
                    console.log(`🎨 Replaced fill='currentColor' with fill='${normalizedFill}'`);
                } else {
                    console.log(`⚠️ No match for fill='currentColor'`);
                }
            }

            if (modified) {
                await fs.writeFile(svgPath, content, 'utf8');
                console.log(`✅ Updated: ${svgPath}`);
                console.log(`Updated content: ${content}`);
            } else {
                console.log(`ℹ️ No changes made to: ${svgPath}`);
            }
        } catch (err) {
            console.error(`❌ Error processing ${svgPath}:`, err.message);
        }
    }

    async replaceCurrentColorFromView(viewPath, { strokeColor = null, fillColor = null } = {}) {
        try {
            const html = await fs.readFile(viewPath, 'utf8');
            const $ = cheerio.load(html);
            const svgPaths = new Set();

            $('img').each((_, el) => {
                const src = $(el).attr('src');
                if (src && src.includes('.svg')) {
                    const cleanedSrc = src.split('?')[0].split('#')[0];
                    let svgPath;

                    if (cleanedSrc.startsWith('/')) {
                        // Camino relativo a la raíz del servidor, mapeado a public/
                        svgPath = path.join(this.projectRoot, 'public', cleanedSrc.slice(1));
                    } else {
                        // Camino relativo al archivo EJS
                        svgPath = path.resolve(path.dirname(viewPath), cleanedSrc);
                    }

                    // Normaliza el camino para usar barras consistentes
                    svgPath = path.normalize(svgPath);

                    // Logs de depuración
                    // console.log(`Debug - src: ${src}`);
                    // console.log(`Debug - cleanedSrc: ${cleanedSrc}`);
                    // console.log(`Debug - svgPath: ${svgPath}`);
                    // console.log(`Debug - this.outputDir: ${this.outputDir}`);
                    // console.log(`Debug - svgPath.startsWith(this.outputDir): ${svgPath.startsWith(this.outputDir)}`);

                    if (!svgPath.startsWith(this.outputDir)) {
                        console.warn(`⚠️ SVG fuera de outputDir ignorado: ${src}`);
                    } else {
                        svgPaths.add(svgPath);
                    }
                }
            });

            if (svgPaths.size === 0) {
                console.log(`ℹ️ No se encontraron SVGs en ${viewPath}`);
                return;
            }

            console.log(`🔍 SVGs encontrados en ${viewPath}:`);
            for (const svgPath of svgPaths) {
                console.log(`  └─ ${svgPath}`);                
                await this.replaceCurrentColorAttributes(svgPath, { strokeColor, fillColor });
            }
        } catch (err) {
            console.error(`❌ Error al leer vista ${viewPath}: ${err.message}`);
        }
    }
}
